# Generated by Django 3.2 on 2021-04-18 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0005_game_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acro.game')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acro.room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='activegame',
            constraint=models.UniqueConstraint(fields=('room', 'game'), name='active_game_unique'),
        ),
    ]
