# Generated by Django 3.2 on 2021-04-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0006_auto_20210418_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='phase',
        ),
        migrations.AddField(
            model_name='activegame',
            name='phase',
            field=models.CharField(choices=[('G', 'Gathering expansions'), ('V', 'Voting on expansions')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
    ]
