# Generated by Django 3.2 on 2021-04-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0011_rename_acronym_game_acrotext'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='acronym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='acro.acronym'),
        ),
    ]
