# Generated by Django 3.2 on 2021-04-19 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0017_alter_finishedgame_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField()),
                ('phrase', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acro.activegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='latestphrase',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='latest_phrase_one_per_game_user'),
        ),
    ]
