# Generated by Django 3.2 on 2021-04-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0021_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegame',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acro.room'),
        ),
    ]
