# Generated by Django 3.2 on 2021-04-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0022_alter_activegame_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activegame',
            name='phase',
        ),
    ]
