# Generated by Django 3.2 on 2021-04-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=50)),
                ('phase', models.CharField(choices=[('G', 'Gathering expansions'), ('V', 'Voting on expansions'), ('F', 'Game finished')], default='G', max_length=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acro.room')),
            ],
        ),
    ]
