# Generated by Django 3.2 on 2021-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0002_game_room'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('slug',), name='slug_unique'),
        ),
    ]
