# Generated by Django 3.2 on 2021-04-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0007_auto_20210418_2054'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activegame',
            name='active_game_unique',
        ),
        migrations.AddConstraint(
            model_name='activegame',
            constraint=models.UniqueConstraint(fields=('room',), name='one_active_game_per_room'),
        ),
    ]
