# Generated by Django 3.2 on 2021-04-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0010_acronym_unique_acronyms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='acronym',
            new_name='acrotext',
        ),
    ]
