# Generated by Django 3.2 on 2021-04-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acro', '0018_latest_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestphrase',
            name='phrase',
            field=models.CharField(max_length=500),
        ),
    ]
