# docker-compose.yml - declarative architecture of acronyms.io dev environment
#
# launch the network with:  ~/acronyms.io$ docker-compose up
#

services:

  # tiny linux distro for poking around the network
  alpine:
    image: alpine
    container_name: acro-alpine
    command: ifconfig
    networks:
      acro_net:
        ipv4_address: 172.16.1.2

  # database server
  postgres:
    image: postgres:9.6-alpine
    container_name: acro-postgres
    environment: 
      POSTGRES_DB: acro_dev
      POSTGRES_USER: acro_dev
      POSTGRES_PASSWORD: acro_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      acro_net:
        ipv4_address: 172.16.1.3

  # python/django api
  api:
    container_name: acro-api
    build:
      context: api
    depends_on:
      - 'postgres'
    volumes:
      - type: bind
        source: ./api
        target: /api
    networks:
      acro_net:
        ipv4_address: 172.16.1.4

  # python/django background task processor
  bg-tasks:
    container_name: acro-bg-tasks
    build:
      context: api
      dockerfile: Dockerfile.bg-tasks
    depends_on:
      - 'postgres'
    volumes:
      - type: bind
        source: ./api
        target: /api

        # we're sharing the same bind-mount with the API server
        # so make sure we can't make changes to it
        read_only: true
    networks:
      acro_net:
        ipv4_address: 172.16.1.8

  # react frontend ui
  web:
    container_name: acro-web
    build:
      context: web
    depends_on:
      - 'api'
    volumes:
      - type: bind
        source: ./web
        target: /web

      # host the container's node_modules as a local docker-managed volume
      - nodemodules-hosted:/web/node_modules
    networks:
      acro_net:
        ipv4_address: 172.16.1.5

  # nginx web proxy
  nginx:
    container_name: acro-nginx
    build:
      context: nginx
    depends_on:
      - 'api'
      - 'web'
    ports:
      - '80:80'
    networks:
      acro_net:
        ipv4_address: 172.16.1.6

  # postgres admin interface
  pgadmin:
    container_name: acro-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8006:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - 'postgres'
    networks:
      acro_net:
        ipv4_address: 172.16.1.7



# define our subnet 172.16.1.*
networks:
  acro_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.16.1.0/24
          gateway: 172.16.1.1


# docker-managed local volumes that will persist between restarts of the containers
volumes:
  postgres-data:
  pgadmin-data:
  nodemodules-hosted:

