
# get a pre-built server from the docker hub with only python installed
FROM python:3.8

# this is bind-mounted (in docker-compose.yml) to our local ~/acronyms.io/api
WORKDIR /api

# set up django and install acro's dependencies
COPY requirements.txt /api
RUN pip3 install -r requirements.txt --no-cache-dir

# install python's production web server (launched from the docker-compose file)
RUN pip3 install gunicorn

